#!/usr/bin/env bash
# Merges provider keys from the current environment into a .env file, keeping
# whatever else that file already holds.
#
# The demos used to do `write-env.sh > .env`, which truncates the file before
# writing. That deleted a key a reader had put there by hand — the setup the
# demo READMEs still document — along with the AEGIS_KEY_PEPPER generated by
# ensure-pepper.sh on an earlier run. Nothing here removes a line it is not
# itself replacing.
#
# Callers source the .env before calling this, so a value already in the file
# is also in the environment by now and is rewritten with the same value.
set -euo pipefail

ENV_FILE="${1:-.env}"
SHARED_DIR="$(cd "$(dirname "$0")" && pwd)"

[ -f "$ENV_FILE" ] || : > "$ENV_FILE"

incoming=$(mktemp)
trap 'rm -f "$incoming"' EXIT
"${SHARED_DIR}/write-env.sh" > "$incoming"

while IFS= read -r line; do
  case "$line" in '' | '#'*) continue ;; esac
  name=${line%%=*}
  if grep -qE "^${name}=" "$ENV_FILE"; then
    kept=$(mktemp)
    grep -vE "^${name}=" "$ENV_FILE" > "$kept" || true
    mv "$kept" "$ENV_FILE"
  fi
  printf '%s\n' "$line" >> "$ENV_FILE"
done < "$incoming"
