#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

DEMO_KEY="aegis-demo-quickstart"
GATEWAY_PORT="${GATEWAY_PORT:-8080}"
GATEWAY_URL="${GATEWAY_URL:-http://localhost:${GATEWAY_PORT}}"

# ── Provider selection ───────────────────────────────────────────
#
# No provider key is required. What this demo shows is policy evaluation,
# which runs before any provider call and is unaffected by which provider is
# configured. With no key the permitted requests are answered by the mock
# provider (internal/router/adapters/mock.go).
# Keys may be exported in the shell, or already sitting in the .env this demo's
# README tells the reader to create. Load that file first so a key living only
# there still counts, and never truncate it: it also carries the pepper
# generated by an earlier run. A key exported in the shell wins over the file.
# shellcheck disable=SC1091
. ../shared/load-env.sh .env

if [ -n "${OPENAI_API_KEY:-}" ] || [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  ../shared/merge-env.sh .env
  export AEGIS_MOCK_PROVIDER=""
  echo "Using a real provider: a key was found."
else
  [ -f .env ] || : > .env
  export AEGIS_MOCK_PROVIDER="true"
  echo "Running against a mock provider. No request will reach a real one."
fi

# The gateway and keygen both exit unless AEGIS_KEY_PEPPER is set (min 32
# chars), and Compose only reaches the gateway through env_file — so make sure
# .env carries one before starting the stack.
../shared/ensure-pepper.sh .env

# ── Start ────────────────────────────────────────────────────────
echo "Building and starting AEGIS custom-policies demo…"
docker compose up --build -d

../shared/wait-for-gateway.sh "${GATEWAY_URL}"

cat <<'BANNER'

============================================
  AEGIS Custom Policies Demo
============================================

BANNER

# ── ACT 1 — Competitor mention policy ────────────────────────────
echo "=== ACT 1: Restricted Term Policy ==="
echo ""
echo "Policy file: policies/restricted-terms.rego"
cat policies/restricted-terms.rego
echo ""

echo "--- Blocked request (mentions a restricted term) ---"
curl -s -X POST "${GATEWAY_URL}/v1/chat/completions" \
  -H "Authorization: Bearer ${DEMO_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"model":"aegis-fast","messages":[{"role":"user","content":"What is the current status of Project Ironwood?"}]}' \
  | jq '{status: .error.code, reason: .error.message}'
echo ""

echo "--- Clean request (no restricted term) ---"
curl -s -X POST "${GATEWAY_URL}/v1/chat/completions" \
  -H "Authorization: Bearer ${DEMO_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"model":"aegis-fast","messages":[{"role":"user","content":"What are the benefits of an AI gateway?"}]}' \
  | jq '{model: .model, content: .choices[0].message.content[:120]}'
echo ""

# ── ACT 2 — Topic restriction policy ─────────────────────────────
echo "=== ACT 2: Topic Restriction Policy ==="
echo ""
echo "Policy file: policies/topic-restriction.rego"
cat policies/topic-restriction.rego
echo ""

echo "--- Blocked request (financial topic from non-finance team) ---"
curl -s -X POST "${GATEWAY_URL}/v1/chat/completions" \
  -H "Authorization: Bearer ${DEMO_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"model":"aegis-fast","messages":[{"role":"user","content":"What is the best trading strategy for tech stocks?"}]}' \
  | jq '{status: .error.code, reason: .error.message}'
echo ""

# ── ACT 3 — Audit log ────────────────────────────────────────────
echo "=== ACT 3: Audit Log ==="
echo ""
echo "--- All policy violations logged ---"
docker exec aegis-demo-postgres psql -U aegis -d aegis -c "
  SELECT event_type, error_message, timestamp
  FROM audit_events
  WHERE event_type = 'filter_block'
  ORDER BY timestamp DESC LIMIT 5;" 2>/dev/null || echo "(audit table not yet populated)"
echo ""
echo "Every denial is recorded regardless of which policy fired."
echo ""

cat <<'EOF'
============================================
  Demo complete!
============================================

  Stop: docker compose down -v

EOF
