#!/usr/bin/env bash
#
# Regenerate the model alias table in README.md from configs/models.yaml.
#
#   mise run docs:models          rewrite README.md in place
#   mise run docs:models:check    fail if README.md is out of date (used by CI)
#
# The table names upstream providers and the specific models each alias routes
# to. Those names go stale, and a stale table on the front page of a project
# whose whole argument is that every claim points at a file is worse than no
# table. So it is generated from the config that actually does the routing,
# between marker comments, and CI fails if the committed README differs.
#
# Output goes between:
#   <!-- BEGIN GENERATED MODEL TABLE -->
#   <!-- END GENERATED MODEL TABLE -->

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODELS_YAML="${REPO_ROOT}/configs/models.yaml"
README="${REPO_ROOT}/README.md"

BEGIN_MARKER="<!-- BEGIN GENERATED MODEL TABLE -->"
END_MARKER="<!-- END GENERATED MODEL TABLE -->"

CHECK_ONLY=false
[ "${1:-}" = "--check" ] && CHECK_ONLY=true

render_table() {
  MODELS_YAML="$MODELS_YAML" python3 - <<'PY'
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

with open(os.environ["MODELS_YAML"]) as fh:
    models = (yaml.safe_load(fh) or {}).get("models") or {}

if not models:
    sys.exit("configs/models.yaml declares no models; refusing to write an empty table")

rows = []
for alias in sorted(models):
    spec = models[alias] or {}
    primary = spec.get("primary") or {}
    fallbacks = spec.get("fallback") or []

    # A deprecated alias routes like its target but should read as an alias, not
    # as a fourth independent model somebody might reach for.
    deprecated = spec.get("deprecated_alias")
    if deprecated:
        route = f"*(deprecated alias, routes as `{deprecated}`)*"
    else:
        hops = [primary] + list(fallbacks)
        route = " then ".join(
            f"{h.get('provider', '?')} `{h.get('model', '?')}`" for h in hops if h
        )

    # The ceiling is per route. They agree in every alias shipped today; if one
    # ever does not, say so rather than silently reporting the primary's.
    ceilings = []
    for hop in [primary] + list(fallbacks):
        if hop and hop.get("classification_ceiling"):
            ceilings.append(hop["classification_ceiling"])
    unique = sorted(set(ceilings))
    ceiling = unique[0] if len(unique) == 1 else (" / ".join(unique) if unique else "none")

    rows.append(f"| `{alias}` | {route} | {ceiling} |")

print("| Alias | Routes to, in order | Classification ceiling |")
print("|-------|---------------------|------------------------|")
print("\n".join(rows))
PY
}

table="$(render_table)"

generated=$(cat <<EOF
${BEGIN_MARKER}
<!-- Generated by scripts/gen-model-table.sh from configs/models.yaml. -->
<!-- Do not edit by hand: run \`mise run docs:models\`. -->

${table}
${END_MARKER}
EOF
)

if ! grep -qF "$BEGIN_MARKER" "$README" || ! grep -qF "$END_MARKER" "$README"; then
  echo "ERROR: README.md is missing the generated table markers." >&2
  echo "Add these two lines where the table belongs:" >&2
  echo "  ${BEGIN_MARKER}" >&2
  echo "  ${END_MARKER}" >&2
  exit 1
fi

updated=$(BEGIN_MARKER="$BEGIN_MARKER" END_MARKER="$END_MARKER" \
  GENERATED="$generated" README="$README" python3 - <<'PY'
import os

begin, end = os.environ["BEGIN_MARKER"], os.environ["END_MARKER"]
text = open(os.environ["README"]).read()

head, _, rest = text.partition(begin)
_, _, tail = rest.partition(end)
print(head + os.environ["GENERATED"] + tail, end="")
PY
)

if [ "$CHECK_ONLY" = true ]; then
  if [ "$updated" = "$(cat "$README")" ]; then
    echo "README.md model table is up to date with configs/models.yaml"
    exit 0
  fi
  echo "ERROR: README.md model table does not match configs/models.yaml." >&2
  echo "Run: mise run docs:models" >&2
  echo >&2
  diff <(printf '%s' "$(cat "$README")") <(printf '%s' "$updated") >&2 || true
  exit 1
fi

printf '%s' "$updated" > "$README"
echo "README.md model table regenerated from configs/models.yaml"
